spring:
  application:
    name: avaliador-filmes
  datasource:
#    url: jdbc:postgresql://localhost:5432/library
    url: jdbc:h2:mem:teste
    username: sa
    password: password
#    username: postgres
#    password: postgres
    driver-class-name: org.h2.Driver
#    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true   # Habilita o console web do H2
      path: /h2-console  # Caminho para acessar o console
#      settings:
#        web-allow-others: true  # Permite acesso remoto (caso necessário)