spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: {EMAIL_ENV}
    password: ${EMAIL_S_ENV}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  application:
    name: avaliador-filmes
  datasource:
    url: jdbc:h2:mem:teste
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format.sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      group-id: meu-grupo
api:
  security:
    token:
      secret: ${JWT_SECRET:minha-chave-secreta}

feign:
  client:
    config:
      tmdb:
        url: ${TMDB_BASE_URL}
        key: ${TMDB_API_KEY}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org:
      com:
        filmes:
          avaliador: TRACE
      springframework:
        web: DEBUG
        security: TRACE
      hibernate:
        SQL: DEBUG