spring:
  application:
    name: avaliador-filmes
  datasource:
#    url: jdbc:postgresql://localhost:5432/library
    url: jdbc:h2:mem:teste
    username: sa
    password: password
#    username: postgres
#    password: postgres
    driver-class-name: org.h2.Driver
#    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format.sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true   # Habilita o console web do H2
      path: /h2-console  # Caminho para acessar o console
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      settings:
#        web-allow-others: true  # Permite acesso remoto (caso necessário)
api:
  security:
    token:
      secret: ${JWT_SECRET:minha-chave-secreta}