spring:
  application:
    name: avaliador-filmes
  datasource:
#    url: jdbc:postgresql://localhost:5432/library
    url: jdbc:h2:mem:teste
    username: sa
    password: password
#    username: postgres
#    password: postgres
    driver-class-name: org.h2.Driver
#    driver-class-name: org.postgresql.Driver